name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.1
          gemfile: Gemfile
          postgres: 14
        - ruby: "3.0"
          gemfile: gemfiles/activerecord61.gemfile
          postgres: 13
        - ruby: 2.7
          gemfile: gemfiles/activerecord60.gemfile
          postgres: 12
        - ruby: 2.6
          gemfile: gemfiles/activerecord52.gemfile
          postgres: 11
        - ruby: 2.5
          gemfile: gemfiles/activerecord51.gemfile
          postgres: 10
        - ruby: 2.4
          gemfile: gemfiles/activerecord50.gemfile
          postgres: 10
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: ankane/setup-postgres@v1
      with:
        postgres-version: ${{ matrix.postgres }}
        database: pghero_test
        config: |
          shared_preload_libraries = 'pg_stat_statements'
    - run: bundle exec rake test
